title: aminullah personal website
description: >-
  personal website for the work i am doing
lsi: false
safe: true
source: docs/ 
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
